import './globals.css'
import {Inter} from 'next/font/google'
import Header from "@/components/Header";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={"dark"}>
        <body className={inter.className}>
        <main className={"dark:bg-slate-800 dark:text-slate-100"}>
            {children}
        </main>
        </body>

        </html>
    )
}
