# Generated by Django 4.2.2 on 2023-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_task_end_alter_task_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='exmaple title'),
            preserve_default=False,
        ),
    ]
