# Generated by Django 4.2.2 on 2023-06-24 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_task_finished_task_is_active_task_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='supervisor',
        ),
    ]
